"""
===============================================================================
TattvaAI - Correlation Domain Model
===============================================================================

Represents a correlation discovered during an AI investigation.

A Correlation groups multiple Evidence objects that collectively indicate
the same incident, failure pattern, or probable root cause.

Correlations are generated by the Correlation Engine and later consumed
by the Reasoning Engine and Root Cause Engine.

Flow
----
Evidence
        ↓
Correlation Engine
        ↓
Correlation
        ↓
Reasoning Engine
        ↓
Root Cause Engine

===============================================================================
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from app.models.evidence import Evidence


class Correlation(BaseModel):
    """
    Canonical correlation model.
    """

    # -------------------------------------------------------------------------
    # Identification
    # -------------------------------------------------------------------------

    correlation_id: Optional[str] = None

    investigation_id: Optional[str] = None

    source_evidence_id: Optional[str] = None

    target_evidence_id: Optional[str] = None

    relationship: Optional[str] = None

    # -------------------------------------------------------------------------
    # Target Service
    # -------------------------------------------------------------------------

    service_name: str

    # -------------------------------------------------------------------------
    # Classification
    # -------------------------------------------------------------------------

    correlation_type: str = "multi_signal"
    # Temporal
    # Dependency
    # Metric
    # Historical
    # Semantic

    severity: str

    confidence: int = Field(
        ge=0,
        le=100,
    )

    score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    # -------------------------------------------------------------------------
    # AI Summary
    # -------------------------------------------------------------------------

    title: str

    summary: str

    reasoning: list[str] = Field(
        default_factory=list
    )

    # -------------------------------------------------------------------------
    # Correlated Evidence
    # -------------------------------------------------------------------------

    evidence: list[Evidence] = Field(
        default_factory=list
    )

    # -------------------------------------------------------------------------
    # AI Findings
    # -------------------------------------------------------------------------

    possible_causes: list[str] = Field(
        default_factory=list
    )

    impacted_services: list[str] = Field(
        default_factory=list
    )

    impacted_endpoints: list[str] = Field(
        default_factory=list
    )

    # -------------------------------------------------------------------------
    # Statistics
    # -------------------------------------------------------------------------

    evidence_count: int = 0

    average_confidence: float = 0.0

    # -------------------------------------------------------------------------
    # Metadata
    # -------------------------------------------------------------------------

    tags: list[str] = Field(
        default_factory=list
    )

    metadata: dict[str, str] = Field(
        default_factory=dict
    )

    # -------------------------------------------------------------------------
    # Timestamp
    # -------------------------------------------------------------------------

    created_at: datetime = Field(
        default_factory=datetime.utcnow
    )

    # -------------------------------------------------------------------------
    # Helper Properties
    # -------------------------------------------------------------------------

    @property
    def strong(self) -> bool:
        """
        Returns True when the correlation is highly reliable.
        """

        return self.confidence >= 85

    @property
    def weak(self) -> bool:
        """
        Returns True when the correlation confidence is low.
        """

        return self.confidence < 50

    @property
    def multi_service(self) -> bool:
        """
        Returns True when multiple services are impacted.
        """

        return len(self.impacted_services) > 1

    @property
    def has_root_cause_candidates(self) -> bool:
        """
        Returns True if possible causes were identified.
        """

        return len(self.possible_causes) > 0

    # -------------------------------------------------------------------------
    # Utility Methods
    # -------------------------------------------------------------------------

    def add_evidence(
        self,
        item: Evidence,
    ) -> None:
        """
        Adds one evidence object and updates statistics.
        """

        self.evidence.append(item)
        self.evidence_count = len(self.evidence)

        if self.evidence:
            self.average_confidence = (
                sum(e.confidence for e in self.evidence)
                / len(self.evidence)
            )

    def summary_text(self) -> str:
        """
        Returns a concise human-readable summary.
        """

        return (
            f"{self.service_name} | "
            f"{self.correlation_type} | "
            f"{self.evidence_count} evidence | "
            f"{self.confidence}% confidence"
        )
