import React from "react";
import { Dialog } from "primereact/dialog";
import { Button } from "primereact/button";
import { Tag } from "primereact/tag";
import { Divider } from "primereact/divider";

export default function EvidenceProvenanceDialog({ visible, onHide, sourceData }) {
    if (!sourceData) return null;

    const {
        provider = "Mock / Demo",
        providerKey = "mock",
        mode = "DEMO",
        signalType = "Distributed Trace",
        sourceId = null,
        timeRange = "Last 15 minutes",
        service = "api-gateway",
        region = "us-east-1",
        acquisitionMethod = "",
        sourceUrl = null,
        isMock = false,
        agentName = null,
        description = ""
    } = sourceData;

    return (
        <Dialog
            header={
                <div className="flex align-items-center gap-2">
                    <i className="pi pi-compass text-primary text-xl"></i>
                    <div>
                        <span className="font-bold text-base text-900 block">
                            Telemetry Provenance & Source Inspection
                        </span>
                        <span className="text-xs text-500 font-normal">
                            Where did this evidence come from?
                        </span>
                    </div>
                </div>
            }
            visible={visible}
            onHide={onHide}
            style={{ width: "90vw", maxWidth: "560px" }}
            contentStyle={{ maxHeight: "calc(85vh - 110px)", overflowY: "auto", padding: "1rem 1.25rem" }}
            footer={
                <div className="flex justify-content-between align-items-center gap-2 pt-2">
                    <div className="text-xs">
                        {isMock ? (
                            <span className="text-orange-600 font-medium flex align-items-center gap-1">
                                <i className="pi pi-box text-xs"></i>
                                Synthetic Demonstration Data
                            </span>
                        ) : (
                            <span className="text-green-600 font-medium flex align-items-center gap-1">
                                <i className="pi pi-check-circle text-xs"></i>
                                Verified Production Telemetry
                            </span>
                        )}
                    </div>
                    <Button
                        label="Close"
                        icon="pi pi-times"
                        severity="secondary"
                        size="small"
                        outlined
                        onClick={onHide}
                    />
                </div>
            }
        >
            <div className="flex flex-column gap-3 pt-1">
                {/* Header Status Row */}
                <div className="flex align-items-center justify-content-between surface-ground px-3 py-2 border-round border-1 surface-border">
                    <div className="flex align-items-center gap-2">
                        <i className={isMock ? "pi pi-box text-orange-500" : "pi pi-cloud text-primary"}></i>
                        <span className="font-semibold text-sm text-900">{provider}</span>
                        <span className="text-xs text-500">({agentName ? `${agentName} Stage` : signalType})</span>
                    </div>
                    <Tag
                        value={isMock ? "SYNTHETIC DEMO" : "LIVE TELEMETRY"}
                        severity={isMock ? "warning" : "success"}
                        className="text-xs font-bold px-2 py-0"
                    />
                </div>

                {/* Synthetic Warning if Mock */}
                {isMock && (
                    <div className="surface-orange-50 p-2 border-round border-1 border-orange-200">
                        <div className="flex align-items-start gap-2">
                            <i className="pi pi-info-circle text-orange-600 text-xs mt-1"></i>
                            <div className="text-xs text-orange-900 line-height-2">
                                <strong>Deterministic Demo Notice:</strong> Generated by the Mock/Demo provider for offline demonstration and evaluation.
                            </div>
                        </div>
                    </div>
                )}

                {/* 2-Column Responsive Information Grid */}
                <div className="surface-card border-round border-1 surface-border p-3">
                    <div className="grid">
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">Provider</span>
                            <span className="font-semibold text-800 text-sm">{provider}</span>
                        </div>
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">Signal</span>
                            <span className="font-semibold text-800 text-sm">{signalType}</span>
                        </div>
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">Service / Resource</span>
                            <span className="font-mono text-800 text-sm font-semibold">{service}</span>
                        </div>
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">Analysis Window</span>
                            <span className="font-semibold text-800 text-sm">{timeRange}</span>
                        </div>
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">Source Identifier</span>
                            <span className="font-mono text-xs text-800 block overflow-hidden text-overflow-ellipsis font-semibold">
                                {sourceId || (isMock ? "mock-trace-id" : "N/A")}
                            </span>
                        </div>
                        <div className="col-12 sm:col-6 py-1">
                            <span className="text-500 font-medium text-xs block">AWS Region</span>
                            <span className="font-mono text-800 text-sm font-semibold">{region}</span>
                        </div>
                    </div>
                </div>

                <Divider className="my-1" />

                {/* How TattvaAI Obtained This Evidence */}
                <div>
                    <span className="text-700 font-semibold text-xs block mb-1">
                        How TattvaAI Obtained This Evidence
                    </span>
                    <p className="text-600 text-xs line-height-3 m-0 surface-ground p-2 border-round border-1 surface-border">
                        {acquisitionMethod || (
                            isMock
                                ? "Generated through TattvaAI's deterministic offline synthetic telemetry engine for payments degradation demonstration."
                                : `Retrieved directly from ${provider} via backend API/SDK integration using IAM execution credentials.`
                        )}
                    </p>
                </div>

                <Divider className="my-1" />

                {/* Source / Console */}
                <div>
                    <span className="text-700 font-semibold text-xs block mb-1">
                        Source / Console
                    </span>
                    {sourceUrl ? (
                        <div className="flex flex-column sm:flex-row sm:align-items-center justify-content-between surface-green-50 border-1 border-green-200 border-round p-2 gap-2">
                            <span className="text-xs text-green-700 font-medium flex align-items-center gap-1">
                                <i className="pi pi-check text-green-600"></i>
                                Verified deep link available
                            </span>
                            <a
                                href={sourceUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                style={{ textDecoration: "none" }}
                            >
                                <Button
                                    label="View in AWS Console"
                                    icon="pi pi-external-link"
                                    size="small"
                                    className="btn-primary"
                                />
                            </a>
                        </div>
                    ) : (
                        <div className="text-xs text-600 surface-ground p-2 border-round border-1 surface-border">
                            {isMock ? (
                                <span>External console link unavailable: Mock evidence is synthetic and does not exist in an external observability platform.</span>
                            ) : sourceId ? (
                                <div>
                                    <span className="font-medium text-700 block">Source available in AWS {provider}:</span>
                                    <span className="font-mono text-xs text-500">Trace / Resource ID: {sourceId}</span>
                                </div>
                            ) : (
                                <span>No external deep link configured for this telemetry signal.</span>
                            )}
                        </div>
                    )}
                </div>
            </div>
        </Dialog>
    );
}
