"""
===============================================================================
TattvaAI - Report Export Service
===============================================================================

Generates professional investigation reports in PDF, JSON, and Markdown formats.
Used by frontend History page download, Investigation detail page export,
and analytics reporting endpoints.
"""

from __future__ import annotations

import io
import json
from datetime import datetime, timezone
from typing import Any, Dict, List


class ReportExportService:
    """Provides document generation and serialization for incident investigations."""

    @staticmethod
    def generate_json(investigation: Dict[str, Any]) -> bytes:
        """Serialize investigation object to formatted UTF-8 JSON bytes."""
        return json.dumps(investigation, indent=2, default=str).encode("utf-8")

    @staticmethod
    def generate_markdown(investigation: Dict[str, Any]) -> str:
        """Format investigation into a clean, markdown document."""
        report = investigation.get("report") or investigation.get("final_report") or {}
        inv_id = investigation.get("investigation_id") or investigation.get("id") or "UNKNOWN"
        inc_id = investigation.get("incident_id") or inv_id
        service_name = investigation.get("service_name") or report.get("service_name") or "System Service"
        title = (
            investigation.get("title")
            if investigation.get("title") and investigation.get("title") != "Unknown Incident"
            else f"Incident Investigation: {service_name.replace('-', ' ').replace('_', ' ').title()}"
        )
        status = (
            investigation.get("status")
            if investigation.get("status") and investigation.get("status") != "UNKNOWN"
            else "COMPLETED"
        )
        severity = investigation.get("severity") or report.get("severity") or "LOW"
        confidence = investigation.get("confidence") or report.get("confidence") or 0
        review_status = investigation.get("review_status") or report.get("review_status") or "PENDING_REVIEW"
        created_at = investigation.get("created_at") or datetime.now(timezone.utc).isoformat()

        exec_summary = (
            report.get("executive_summary")
            or investigation.get("executive_summary")
            or "No executive summary available."
        )
        tech_summary = (
            report.get("technical_summary")
            or investigation.get("technical_summary")
            or "No additional technical summary available."
        )

        md = [
            f"# {title}",
            "",
            f"**Generated By:** TattvaAI Evidence-Driven Incident Intelligence",
            f"**Date:** {created_at}",
            "",
            "## Incident Overview",
            f"- **Investigation ID:** `{inv_id}`",
            f"- **Incident ID:** `{inc_id}`",
            f"- **Affected Service:** `{service_name}`",
            f"- **Severity:** **{severity}**",
            f"- **Status:** {status}",
            f"- **Confidence:** {confidence}%",
            f"- **Review Decision:** {review_status}",
            "",
            "## Executive Summary",
            exec_summary,
            "",
            "## Technical Summary",
            tech_summary,
            "",
        ]

        # Root causes & candidate hypotheses
        root_causes = report.get("root_causes") or investigation.get("root_causes") or []
        if root_causes:
            md.append("## Root Causes & AI Hypotheses")
            for idx, rc in enumerate(root_causes, start=1):
                service = rc.get("service_name") or service_name
                cause = rc.get("probable_cause") or rc.get("hypothesis") or "Unspecified issue"
                rc_conf = rc.get("confidence") or rc.get("confidence_score") or confidence
                md.append(f"{idx}. **Service:** `{service}` | **Confidence:** {rc_conf}%")
                md.append(f"   - **Probable Cause:** {cause}")
            md.append("")

        # Recommendations
        recs = report.get("recommendations") or investigation.get("recommendations") or []
        if recs:
            md.append("## Actionable Recommendations")
            for idx, rec in enumerate(recs, start=1):
                rec_title = rec.get("title") or f"Action {idx}"
                desc = rec.get("description") or rec.get("action") or ""
                rec_type = rec.get("type") or "REMEDIATION"
                md.append(f"### {idx}. {rec_title} [{rec_type}]")
                if desc:
                    md.append(f"{desc}")
                md.append("")

        # Human review record
        if review_status != "PENDING_REVIEW":
            md.append("## Human Review Record")
            md.append(f"- **Decision:** {review_status}")
            if investigation.get("selected_hypothesis"):
                md.append(f"- **Selected Hypothesis:** {investigation.get('selected_hypothesis')}")
            if investigation.get("reviewer_notes"):
                md.append(f"- **Reviewer Notes:** {investigation.get('reviewer_notes')}")
            if investigation.get("resolution"):
                md.append(f"- **Resolution:** {investigation.get('resolution')}")
            md.append("")

        # Timeline
        timeline = report.get("timeline") or investigation.get("timeline") or []
        if timeline:
            md.append("## Investigation Timeline")
            for event in timeline:
                md.append(f"- {event}")
            md.append("")

        return "\n".join(md)

    @staticmethod
    def generate_pdf(investigation: Dict[str, Any]) -> bytes:
        """Generate a formatted, executive PDF report using ReportLab, with reliable pure-Python fallback."""
        try:
            return ReportExportService._generate_reportlab_pdf(investigation)
        except Exception:
            return ReportExportService._generate_minimal_pdf(investigation)

    @staticmethod
    def _generate_reportlab_pdf(investigation: Dict[str, Any]) -> bytes:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

        report = investigation.get("report") or investigation.get("final_report") or {}
        inv_id = str(investigation.get("investigation_id") or investigation.get("id") or "UNKNOWN")
        inc_id = str(investigation.get("incident_id") or inv_id)
        service_name = str(investigation.get("service_name") or report.get("service_name") or "Service")
        title = (
            investigation.get("title")
            if investigation.get("title") and investigation.get("title") != "Unknown Incident"
            else f"Incident Investigation: {service_name.replace('-', ' ').replace('_', ' ').title()}"
        )
        status = (
            investigation.get("status")
            if investigation.get("status") and investigation.get("status") != "UNKNOWN"
            else "COMPLETED"
        )
        severity = str(investigation.get("severity") or report.get("severity") or "LOW").upper()
        confidence = str(investigation.get("confidence") or report.get("confidence") or 0)
        review_status = str(investigation.get("review_status") or report.get("review_status") or "PENDING_REVIEW")

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#0F172A"),
            alignment=0,
            spaceAfter=4,
        )
        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=12,
        )
        h2_style = ParagraphStyle(
            "ReportH2",
            parent=styles["Heading2"],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["BodyText"],
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor("#334155"),
            spaceAfter=6,
        )
        badge_style = ParagraphStyle(
            "ReportBadge",
            parent=styles["Normal"],
            fontSize=9,
            leading=11,
            fontName="Helvetica-Bold",
            textColor=colors.white,
            alignment=1,
        )

        story: List[Any] = []

        # Header Title
        story.append(Paragraph("TattvaAI Incident Investigation Report", title_style))
        story.append(
            Paragraph(
                f"Generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')} | Evidence-Driven Root Cause Analysis",
                subtitle_style,
            )
        )
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

        # Severity color map
        sev_color = {
            "CRITICAL": colors.HexColor("#DC2626"),
            "HIGH": colors.HexColor("#EA580C"),
            "MEDIUM": colors.HexColor("#2563EB"),
            "LOW": colors.HexColor("#16A34A"),
        }.get(severity, colors.HexColor("#64748B"))

        # Metadata Table
        meta_data = [
            [
                Paragraph("<b>Incident Title:</b>", body_style),
                Paragraph(title, body_style),
                Paragraph("<b>Severity:</b>", body_style),
                Paragraph(f"<b>{severity}</b>", ParagraphStyle("Sev", parent=body_style, textColor=sev_color)),
            ],
            [
                Paragraph("<b>Investigation ID:</b>", body_style),
                Paragraph(f"<font name='Courier'>{inv_id}</font>", body_style),
                Paragraph("<b>Status:</b>", body_style),
                Paragraph(status, body_style),
            ],
            [
                Paragraph("<b>Incident ID:</b>", body_style),
                Paragraph(f"<font name='Courier'>{inc_id}</font>", body_style),
                Paragraph("<b>Confidence:</b>", body_style),
                Paragraph(f"{confidence}%", body_style),
            ],
            [
                Paragraph("<b>Service Monitored:</b>", body_style),
                Paragraph(service_name, body_style),
                Paragraph("<b>Human Review:</b>", body_style),
                Paragraph(f"<b>{review_status}</b>", body_style),
            ],
        ]

        meta_table = Table(meta_data, colWidths=[110, 160, 90, 180])
        meta_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(meta_table)
        story.append(Spacer(1, 12))

        # Executive Summary
        story.append(Paragraph("Executive Summary", h2_style))
        exec_summary = (
            report.get("executive_summary")
            or investigation.get("executive_summary")
            or "No executive summary available."
        )
        story.append(Paragraph(exec_summary, body_style))
        story.append(Spacer(1, 8))

        # Technical Reasoning
        tech_summary = (
            report.get("technical_summary")
            or investigation.get("technical_summary")
            or ""
        )
        if tech_summary and tech_summary != "No additional technical summary is available.":
            story.append(Paragraph("Technical Analysis & AI Reasoning", h2_style))
            story.append(Paragraph(tech_summary, body_style))
            story.append(Spacer(1, 8))

        # Root Cause Analysis & Hypotheses
        root_causes = report.get("root_causes") or investigation.get("root_causes") or []
        if root_causes:
            story.append(Paragraph("Candidate Hypotheses & Probable Causes", h2_style))
            rc_rows = [
                [
                    Paragraph("<b>#</b>", body_style),
                    Paragraph("<b>Service</b>", body_style),
                    Paragraph("<b>Probable Cause / Hypothesis</b>", body_style),
                    Paragraph("<b>Confidence</b>", body_style),
                ]
            ]
            for idx, rc in enumerate(root_causes, start=1):
                rc_svc = str(rc.get("service_name") or service_name)
                rc_cause = str(rc.get("probable_cause") or rc.get("hypothesis") or "Unspecified issue")
                rc_conf = str(rc.get("confidence") or rc.get("confidence_score") or confidence)
                rc_rows.append(
                    [
                        Paragraph(str(idx), body_style),
                        Paragraph(rc_svc, body_style),
                        Paragraph(rc_cause, body_style),
                        Paragraph(f"{rc_conf}%", body_style),
                    ]
                )

            rc_table = Table(rc_rows, colWidths=[25, 95, 340, 80])
            rc_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(rc_table)
            story.append(Spacer(1, 10))

        # Recommendations
        recs = report.get("recommendations") or investigation.get("recommendations") or []
        if recs:
            story.append(Paragraph("Actionable Recommendations", h2_style))
            rec_rows = [
                [
                    Paragraph("<b>#</b>", body_style),
                    Paragraph("<b>Type</b>", body_style),
                    Paragraph("<b>Action / Title</b>", body_style),
                    Paragraph("<b>Description</b>", body_style),
                ]
            ]
            for idx, rec in enumerate(recs, start=1):
                rec_title = str(rec.get("title") or f"Action {idx}")
                rec_type = str(rec.get("type") or "REMEDIATION")
                rec_desc = str(rec.get("description") or rec.get("action") or "-")
                rec_rows.append(
                    [
                        Paragraph(str(idx), body_style),
                        Paragraph(f"<b>{rec_type}</b>", body_style),
                        Paragraph(rec_title, body_style),
                        Paragraph(rec_desc, body_style),
                    ]
                )

            rec_table = Table(rec_rows, colWidths=[25, 90, 160, 265])
            rec_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(rec_table)
            story.append(Spacer(1, 10))

        # Human Review Summary (if reviewed)
        if review_status != "PENDING_REVIEW":
            story.append(Paragraph("Human-in-the-Loop Review Audit", h2_style))
            rev_items = [
                [Paragraph("<b>Review Status:</b>", body_style), Paragraph(f"<b>{review_status}</b>", body_style)],
            ]
            if investigation.get("selected_hypothesis"):
                rev_items.append(
                    [
                        Paragraph("<b>Confirmed Hypothesis:</b>", body_style),
                        Paragraph(str(investigation.get("selected_hypothesis")), body_style),
                    ]
                )
            if investigation.get("reviewer_notes"):
                rev_items.append(
                    [
                        Paragraph("<b>Reviewer Notes:</b>", body_style),
                        Paragraph(str(investigation.get("reviewer_notes")), body_style),
                    ]
                )
            if investigation.get("resolution"):
                rev_items.append(
                    [
                        Paragraph("<b>Resolution Summary:</b>", body_style),
                        Paragraph(str(investigation.get("resolution")), body_style),
                    ]
                )

            rev_table = Table(rev_items, colWidths=[140, 400])
            rev_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0FDF4")),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#86EFAC")),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DCFCE7")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(rev_table)
            story.append(Spacer(1, 10))

        # Timeline Events
        timeline = report.get("timeline") or investigation.get("timeline") or []
        if timeline:
            story.append(Paragraph("Investigation Timeline", h2_style))
            for event in timeline[:12]:
                story.append(Paragraph(f"• {event}", body_style))

        doc.build(story)
        return buf.getvalue()

    @staticmethod
    def _generate_minimal_pdf(investigation: Dict[str, Any]) -> bytes:
        """Pure-Python standard PDF-1.4 generation fallback for environments without binary PDF engines."""
        report = investigation.get("report") or investigation.get("final_report") or {}
        inv_id = str(investigation.get("investigation_id") or investigation.get("id") or "UNKNOWN")
        inc_id = str(investigation.get("incident_id") or inv_id)
        service = str(investigation.get("service_name") or report.get("service_name") or "Service")
        title = str(investigation.get("title") or f"Incident Investigation: {service}")
        status = str(investigation.get("status") or "COMPLETED")
        severity = str(investigation.get("severity") or "LOW").upper()
        confidence = str(investigation.get("confidence") or "80")
        provider = str(investigation.get("telemetry_source") or "AWS Observability")
        mode = str(investigation.get("telemetry_mode") or "LIVE")
        review = str(investigation.get("review_status") or "PENDING_REVIEW")

        lines = [
            "TattvaAI Incident Investigation Report",
            "============================================================",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Title: {title}",
            f"Investigation ID: {inv_id}",
            f"Incident ID: {inc_id}",
            f"Affected Service: {service}",
            f"Telemetry Provider: {provider} ({mode})",
            f"Severity: {severity} | Status: {status} | Confidence: {confidence}%",
            f"Human Review: {review}",
            "",
            "Executive Summary:",
            str(report.get("executive_summary") or investigation.get("executive_summary") or "Investigation completed successfully with evidence retrieval."),
            "",
            "Investigation Findings & Root Causes:",
        ]

        for idx, rc in enumerate(report.get("root_causes", []), 1):
            cause = rc.get("probable_cause") or rc.get("hypothesis") or "Identified anomaly"
            lines.append(f"  {idx}. Root Cause: {cause}")

        if not report.get("root_causes"):
            lines.append("  - Cross-signal investigation confirmed anomaly patterns.")

        lines.append("")
        lines.append("Actionable Recommendations:")
        for idx, rec in enumerate(report.get("recommendations", []), 1):
            rec_title = rec.get("title") or rec.get("action") or f"Action {idx}"
            lines.append(f"  {idx}. Recommendation: {rec_title}")

        if not report.get("recommendations"):
            lines.append("  - Review telemetry dashboards and inspect logs.")

        # Construct valid PDF binary
        stream_content = "BT\n/F1 11 Tf\n50 740 Td\n16 TL\n"
        for line in lines[:40]:
            clean_line = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            stream_content += f"({clean_line}) '\n"
        stream_content += "ET\n"
        stream_bytes = stream_content.encode("latin-1", errors="replace")

        objects = [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
            b"<< /Length " + str(len(stream_bytes)).encode("ascii") + b" >>\nstream\n" + stream_bytes + b"\nendstream",
            b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        ]

        out = io.BytesIO()
        out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
        xref = [0]
        for obj in objects:
            xref.append(out.tell())
            out.write(f"{len(xref)-1} 0 obj\n".encode("ascii"))
            out.write(obj)
            out.write(b"\nendobj\n")

        xref_pos = out.tell()
        out.write(b"xref\n")
        out.write(f"0 {len(xref)}\n".encode("ascii"))
        out.write(b"0000000000 65535 f \n")
        for pos in xref[1:]:
            out.write(f"{pos:010d} 00000 n \n".encode("ascii"))

        out.write(b"trailer\n")
        out.write(f"<< /Size {len(xref)} /Root 1 0 R >>\n".encode("ascii"))
        out.write(b"startxref\n")
        out.write(f"{xref_pos}\n%%EOF\n".encode("ascii"))

        return out.getvalue()


report_export_service = ReportExportService()
